pipeline {
    agent any
    tools {
      maven "mymaven"
    }
    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Deploy') {
            steps {
                sshagent(['jentomcat']) {
   sh "scp -o StrictHostKeyChecking=no target/*.war ansadmin@18.207.141.177:/home/ansadmin/tomcat/webapps"
   }
            }
        }
    }
}
